name: Build Next.js web application
on: 
  push:
    branches:
      - nextjs
jobs: 
  build-node:
    name: Build Project
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
      - name: yeri göster
        run: ls -al .next/
      - name: Upload static site content
        uses: actions/upload-artifact@v3
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        with:
         name: static-site
         path: .next/
